Repository jiro4989/sayhissatsuwaza, pull requests merged in 2021-06, with the labels that each got.

#5 feat: 文字数を調整して語呂が良くなるようにした #1
  src/sayhissatsuwaza.nim
Labels: feature

#7 feat: コマンドラインオプションを追加 #6
  src/sayhissatsuwaza.nim
Labels: feature

#11 chore: cligenを追加 #10
  sayhissatsuwaza.nimble
  src/sayhissatsuwaza.nim
Labels: feature

#12 feat: オプション引数countにより出力回数を制御できるようにした #9
  src/sayhissatsuwaza.nim
Labels: feature

#16 多言語化対応可能な仕組みに変更 #15
  .monit.yml
  src/sayhissatsuwaza.nim
  src/sayhissatsuwazapkg/lang/lang_en_US.nim
  src/sayhissatsuwazapkg/lang/lang_ja_JP.nim
  src/sayhissatsuwazapkg/lang/lang_zh_CN.nim
  src/sayhissatsuwazapkg/lang/lang_zh_TW.nim
  src/sayhissatsuwazapkg/types.nim
  src/sayhissatsuwazapkg/utils.nim
Labels: feature

#18 feat: WebUIで生成言語を指定できるようにした #17
  .github/workflows/pages.yml
  .github/workflows/test.yml
  public/index.html
  sayhissatsuwaza.nimble
  src/sayhissatsuwaza.nim
Labels: feature

#22 voice
  public/index.html
Labels: feature, web

#23 feat: 日本語の必殺技の生成方法を変更
  .github/workflows/test.yml
  src/sayhissatsuwazapkg/lang/lang_ja_JP.nim
  tests/config.nims
  tests/test1.nim
Labels: feature

#25 chore: ja_JPモジュール内の重複コードを整理 #24
  .github/workflows/test.yml
  src/sayhissatsuwazapkg/lang/lang_ja_JP.nim
Labels: feature

#26 chore: en_USの実装をja_JPと同じにした #24
  src/sayhissatsuwazapkg/lang/lang_en_US.nim
  src/sayhissatsuwazapkg/lang/lang_ja_JP.nim
  src/sayhissatsuwazapkg/types2.nim
  src/sayhissatsuwazapkg/utils2.nim
Labels: feature

#27 chore: 中国語のモジュールの実装も他のと同じ実装に合わせた #24
  src/sayhissatsuwaza.nim
  src/sayhissatsuwazapkg/lang/lang_en_US.nim
  src/sayhissatsuwazapkg/lang/lang_ja_JP.nim
  src/sayhissatsuwazapkg/lang/lang_zh_CN.nim
  src/sayhissatsuwazapkg/lang/lang_zh_TW.nim
  src/sayhissatsuwazapkg/types.nim
  src/sayhissatsuwazapkg/types2.nim
  src/sayhissatsuwazapkg/utils.nim
  src/sayhissatsuwazapkg/utils2.nim
Labels: chore

#29 feat: 中国語の必殺技のパターンを変更 #15
  src/sayhissatsuwazapkg/lang/lang_zh_CN.nim
  src/sayhissatsuwazapkg/types.nim
Labels: feature

#30 feat: 生成個数を指定可能に変更＋生成時のアニメーションを追加
  public/index.html
Labels: feature

#31 chore: コピーライトを追加 #28
  public/index.html
Labels: chore
